config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :tweets, path: :favorites, only: :index do
    collection do
      post 'refresh'
    end
  end

  get '/profile', to: 'profiles#edit'
  put '/profile', to: 'profiles#update'
  patch '/profile', to: 'profiles#update'

  delete '/disconnect', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'

end

app/models/tweet.rb
class Tweet
  include Mongoid::Document
  include Mongoid::Timestamps

  field :tid, type: String
  field :text, type: String
  field :tweeted_at, type: DateTime

  belongs_to :user

  def self.refresh(user)
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV['TWITTER_KEY']
      config.consumer_secret     = ENV['TWITTER_SECRET']
      config.access_token        = user.access_token
      config.access_token_secret = user.access_secret
    end

    client.favorites.each do |raw_tweet|
      unless where(tid: raw_tweet.id).exists?
        user.tweets << create do |tweet|
          tweet.tid = raw_tweet.id
          tweet.text = raw_tweet.text
          tweet.tweeted_at = raw_tweet.created_at
        end
      end
    end
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  field :provider, type: String
  field :uid, type: String
  field :access_token, type: String
  field :access_secret, type: String

  field :name, type: String
  field :email, type: String

  has_many :tweets

  validates_presence_of :name
  validates_presence_of :email, on: :update

  def self.find_or_create_from_auth(auth)
    find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
      user.name = auth.info.name
      user.access_token = auth.credentials.token
      user.access_secret = auth.credentials.secret
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  responders :flash
  respond_to :html, :xml, :json

  protected

  def require_login
    unless current_user
      flash[:alert] = 'You must be connected to view this page.'
      redirect_to connect_path(origin: request.path)
    end
  end

  private

  def current_user
    user_id = session[:user_id]
    @current_user ||= User.where(id: user_id).first if user_id
  end

  helper_method :current_user
end

app/controllers/logged_controller.rb
class LoggedController < ApplicationController
  before_action :require_login
end

app/controllers/profiles_controller.rb
class ProfilesController < LoggedController
  expose(:user) { current_user }

  def update
    user.attributes = user_params

    if user.save
      respond_with user, location: profile_path
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_from_auth(auth)
    session[:user_id] = user.id
    if user.name? && user.email?
      redirect_to request.env['omniauth.origin'] || root_path
    else
      redirect_to profile_path
    end
  end

  def destroy
    respond_with reset_session, location: root_path
  end

  protected

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/tweets_controller.rb
class TweetsController < LoggedController
  expose(:tweet)
  expose(:tweets) { current_user.tweets }

  def index
  end

  def refresh
    respond_with Tweet.refresh(current_user), location: tweets_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def connect_path(auth_provider, opts = {})
    "/auth/#{auth_provider}".tap do |res|
      opts_query = opts.to_query
      res << "?#{opts_query}" if opts_query.present?
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Favoread</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Favoread', root_path, class: 'navbar-brand' %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Profile', profile_path %></li>
                  <li><%= link_to 'Favorites', tweets_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Disconnect', disconnect_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to 'Connect', connect_path("twitter", origin: request.fullpath) %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav>

    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= simple_form_for(user, url: profile_path) do |f| %>
  <%= f.input :name %>
  <%= f.input :email, as: :email %>
  <%= f.button :submit, 'Save' %>
<% end %>

app/views/profiles/edit.html.erb
<% provide(:title, 'Editing Profile') %>

<h1>Editing Profile</h1>

<%= render 'form' %>

app/views/tweets/index.html.erb
<% tweets.each do |tweet| %>
  <div class="panel panel-default">
    <div class="panel-body">
      <%= auto_link(tweet.text) %>
    </div>
  </div>
<% end %>

<p class="text-center">
  <%= link_to 'Refresh', refresh_tweets_path, method: :post, class: 'btn btn-primary', role: 'button' %>
</p>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h2 class="text-center">Welcome to Favoread</h2>
  <p class="text-center">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis et sapien et dolor auctor vehicula. Praesent convallis sem a gravida faucibus. Proin rutrum orci in ligula feugiat cursus. Vestibulum at felis vitae lectus mattis dictum id vel ipsum.</p>
  <% unless current_user %>
    <p class="text-center">
      <%= link_to(connect_path("twitter", origin: request.fullpath), class: 'btn btn-success btn-lg', role: 'button') do %>
        <span class="glyphicon glyphicon-user"></span> Connect
      <% end %>
    </p>
  <% end %>
</div>